const MAIN_THEME_COLOR = '#1DBF73';
const ACCENT_THEME_COLOR = '#0DE27E';
const CONTAINER_BACKGROUND_COLOR = '#FFFFFF';
const BORDER_COLOR = '#E2E2E2';
const APP_BACKGROUND_COLOR = '#FCFCFC';
const GREY_TEXT_COLOR = '#DEDEDE';

export {
  MAIN_THEME_COLOR,
  ACCENT_THEME_COLOR,
  CONTAINER_BACKGROUND_COLOR,
  BORDER_COLOR,
  APP_BACKGROUND_COLOR,
  GREY_TEXT_COLOR
}